ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
  path: /
  pathType: Prefix
  spec:
    ingressClassName: nginx
  hosts:
    - grafana.example.com
  paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: grafana
          port:
            number: 80
  tls:
    - secretName: grafana-load-dev-tls
      hosts:
        - grafana.example.com

persistence:
  type: pvc
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  finalizers:
    - kubernetes.io/pvc-protection
  extraPvcLabels: {}
  disableWarning: false
  storageClassName: "standard"
  #storageClassName: "csi-disk"

  inMemory:
    enabled: false

  lookupVolumeName: true

adminUser: admin
#adminPassword: ""

admin:
  existingSecret: ""
  userKey: admin-user
  passwordKey: admin-password

