apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:latest
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgres://root:<replace-password>W@<replace-ip>:5432/postgres?sslmode=disable"
              #value: "postgres://postgres:pwadmin@postgres.monitoring.svc.cluster.local:5432/postgres?sslmode=disable"
          volumeMounts:
            - name: queries-config
              mountPath: /etc/postgres_exporter/queries.yaml
              subPath: queries.yaml
      volumes:
        - name: queries-config
          configMap:
            name: postgres-exporter-config
            items:
              - key: queries.yaml
                path: queries.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  ports:
    - port: 9187
      targetPort: 9187
  selector:
    app: postgres-exporter
